export interface CoreValue {
  id: string;
  name: string;
  description: string;
  icon: string;
}

export interface Archetype {
  id: string;
  title: string;
  subtitle: string;
  description: string;
  dominance: number;
  traits: string[];
  motto: string;
  shadow: string;
  icon: string;
}

export interface PerceptionAlignment {
  authorityVsAccessibility: number;
  innovationVsTradition: number;
  provocativeVsReassuring: number;
  specialistVsPolymath: number;
}

export interface IkigaiPillars {
  passion: string;
  mission: string;
  vocation: string;
  profession: string;
  intersection?: string;
}

export interface VoiceProfile {
  tone: string[];
  style?: string;
  vocabulary?: string[];
}

/**
 * Individual color generated by the Color Intelligence engine.
 */
export interface ColorItem {
  role: "primary" | "secondary" | "accent" | "darkNeutral" | "lightNeutral";
  roleTitle: string;
  name: string;
  hex: string;
  rgb: string;
  psychology: string;
  recommendedUsage: string;
  valueAnchor?: string;
}

/**
 * Complete result generated by the Color Intelligence engine.
 */
export interface ColorPaletteResult {
  primary: ColorItem;
  secondary: ColorItem;
  accent: ColorItem;
  darkNeutral: ColorItem;
  lightNeutral: ColorItem;
  derivedFromValues: string[];
  overallStrategy: string;
}

/**
 * Simplified palette used inside the final Brand DNA.
 */
export interface ColorPalette {
  primary: string;
  secondary: string;
  accent: string;
  darkNeutral: string;
  lightNeutral: string;
}

export interface ContentPillar {
  title: string;
  description: string;
}

export interface BrandDNASummary {
  id?: string;

  personName: string;

  title?: string;

  values: string[];

  primaryArchetype: Archetype;

  secondaryArchetype: Archetype;

  purpose: string;

  vision: string;

  voice: VoiceProfile;

  perception: PerceptionAlignment;

  ikigai: IkigaiPillars;

  colorPalette?: ColorPalette;

  strategicManifesto?: string;

  executivePositioning?: string;

  elevatorPitch?: string;

  contentPillars?: ContentPillar[];

  strategicAdvices?: string[];

  completedAt?: string;
}